//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer3.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer3.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is closed.
        /// </summary>
        public static string AccountClosed {
            get {
                return ResourceManager.GetString("AccountClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator needs to be configured for this account.
        /// </summary>
        public static string AccountNotConfiguredWithAuthenticator {
            get {
                return ResourceManager.GetString("AccountNotConfiguredWithAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certificate needs to be configured for this account.
        /// </summary>
        public static string AccountNotConfiguredWithCertificates {
            get {
                return ResourceManager.GetString("AccountNotConfiguredWithCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mobile phone number needs to be configured for this account.
        /// </summary>
        public static string AccountNotConfiguredWithMobilePhone {
            get {
                return ResourceManager.GetString("AccountNotConfiguredWithMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account needs to be verified.
        /// </summary>
        public static string AccountNotVerified {
            get {
                return ResourceManager.GetString("AccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts requires a form of two factor authentication to be configured.
        /// </summary>
        public static string AccountRequiresSecondFactorToAuthenticate {
            get {
                return ResourceManager.GetString("AccountRequiresSecondFactorToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client identifier is required.
        /// </summary>
        public static string ClientIdRequired {
            get {
                return ResourceManager.GetString("ClientIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error logging into the external provider. The Reason message is: {0}.
        /// </summary>
        public static string ExternalProviderError {
            get {
                return ResourceManager.GetString("ExternalProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded failed login attempts.
        /// </summary>
        public static string FailedLoginAttemptsExceeded {
            get {
                return ResourceManager.GetString("FailedLoginAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client application made an invalid request..
        /// </summary>
        public static string invalid_request {
            get {
                return ResourceManager.GetString("invalid_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client application tried to access a resource it does not have access to..
        /// </summary>
        public static string invalid_scope {
            get {
                return ResourceManager.GetString("invalid_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Phone Number.
        /// </summary>
        public static string InvalidMobilephoneNumber {
            get {
                return ResourceManager.GetString("InvalidMobilephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge code or session code is invalid.
        /// </summary>
        public static string InvalidPasswordlessCodes {
            get {
                return ResourceManager.GetString("InvalidPasswordlessCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to signin to this application.
        /// </summary>
        public static string LoginNotAllowed {
            get {
                return ResourceManager.GetString("LoginNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_id is missing.
        /// </summary>
        public static string MissingClientId {
            get {
                return ResourceManager.GetString("MissingClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is missing.
        /// </summary>
        public static string MissingToken {
            get {
                return ResourceManager.GetString("MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select at least one permission..
        /// </summary>
        public static string MustSelectAtLeastOnePermission {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOnePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login provider was not provided..
        /// </summary>
        public static string NoExternalProvider {
            get {
                return ResourceManager.GetString("NoExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account.
        /// </summary>
        public static string NoMatchingExternalAccount {
            get {
                return ResourceManager.GetString("NoMatchingExternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error determining which application you are signing into. Return to the application and try again..
        /// </summary>
        public static string NoSignInCookie {
            get {
                return ResourceManager.GetString("NoSignInCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error authenticating with external provider.
        /// </summary>
        public static string NoSubjectFromExternalProvider {
            get {
                return ResourceManager.GetString("NoSubjectFromExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to send SMS code to provided mobile phone.
        /// </summary>
        public static string NotAbleToSendSmsCode {
            get {
                return ResourceManager.GetString("NotAbleToSendSmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The challenge or session code is not valid, expired or does not exist.
        /// </summary>
        public static string PasswordlessCodeOrSessionNotFound {
            get {
                return ResourceManager.GetString("PasswordlessCodeOrSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL is required.
        /// </summary>
        public static string SslRequired {
            get {
                return ResourceManager.GetString("SslRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string TwoFactorCodeInvalid {
            get {
                return ResourceManager.GetString("TwoFactorCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string TwoFactorCodeRequired {
            get {
                return ResourceManager.GetString("TwoFactorCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has been resent, please enter the new code.
        /// </summary>
        public static string TwoFactorCodeResent {
            get {
                return ResourceManager.GetString("TwoFactorCodeResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client application is not known or is not authorized..
        /// </summary>
        public static string unauthorized_client {
            get {
                return ResourceManager.GetString("unauthorized_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization server does not support the requested response type..
        /// </summary>
        public static string unsupported_response_type {
            get {
                return ResourceManager.GetString("unsupported_response_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Media Type.
        /// </summary>
        public static string UnsupportedMediaType {
            get {
                return ResourceManager.GetString("UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
    }
}
